version: '3'

services:
  rest-type-express:
    build: 
      context: .
      dockerfile: ./docker/rest-type-express/Dockerfile
      args:
        mode: local
    container_name: rest-type-express
    networks:
      - rest-type-network
    ports: 
      - 7000:7000
    depends_on:
      - rest-type-postgres
      - rest-type-mongo
      - rest-type-redis
    environment:
      DB_PG_HOST: base-api-postgres
      DB_MONGO_BASE_URL: mongodb://rest-type-mongo:27017/
      REDIS_URL: redis://rest-type-redis:6379
    restart: always
  rest-type-redis:
    image: redis
    container_name: rest-type-redis
    ports: 
      - 6378:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - rest-type-volume:/data
    networks:
      - rest-type-network
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: rest-api-dev
  rest-type-postgres:
    image: postgres
    container_name: rest-type-postgres
    ports: 
      - 5436:5432
    volumes:
      - rest-type-volume:/var/lib/postgresql/data
    networks:
      - rest-type-network
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: rest-api-dev

  rest-type-mongo:
    image: mongo
    container_name: rest-type-mongo
    ports: 
      - 27020:27017
    volumes:
      - rest-type-volume:/etc/mongo
    networks:
      - rest-type-network
    restart: always
networks:
  rest-type-network:
    name: rest-type-network
volumes:
  rest-type-volume:
    name: rest-type-volume

